pms/urls.py
from django.contrib import admin
from login import views as lviews
from flower import views as fviews
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from news import views as nviews

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', fviews.flower),
    path('accounts/', include('allauth.urls')),
    # path('login/', lviews.login),
    # path('register/', lviews.register, name="register"),
    # path('logout/', lviews.logout),
    # path('flower/', fviews.flower),
    path('create/', fviews.create, name='create'), 
    path('flower/<slug:slug>/', fviews.detail, name='detail'),    
    path('tags/<slug:slug>/', fviews.tags, name='tags'),
    path('flower/edit/<int:pk>/', fviews.edit, name='edit'),
    path('flower/delete/<int:pk>/', fviews.delete, name='delete'),
    path('news/', nviews.news, name='news'),
    path('news/<str:pageindex>/', nviews.news, name='news'),
    path('detail/<int:detailid>/', nviews.detail, name='detail'),
    path('newsadd/', nviews.newsadd),
    path('newsedit/<int:newsid>/', nviews.newsedit),
    path('newsedit/<int:newsid>/<str:edittype>/', nviews.newsedit),
    path('newsdelete/<int:newsid>/', nviews.newsdelete),
    path('newsdelete/<int:newsid>/<str:deletetype>/', nviews.newsdelete),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
from django.db import models

# Create your models here.

flower/models.py
from django.utils.text import slugify
from django.db import models
from django.urls import reverse
from django.utils import timezone

class Category(models.Model): 
    title = models.CharField(max_length=255, default='')

    def __str__(self):
        return self.title

class Tag(models.Model):
    title = models.CharField(max_length=255, default='')
    slug = models.SlugField(blank=True, default='')
    
    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Tag, self).save()
    
class Photo(models.Model):
    image = models.ImageField(upload_to='image/', blank=False, null=False)
    upload_date = models.DateField(default=timezone.now)


# Create your models here.
class Flower(models.Model):
    title = models.CharField(max_length=255, default='')
    description = models.TextField(default='')
    slug = models.SlugField(blank=True, default='')
    category = models.ForeignKey(Category, null=True, on_delete=models.PROTECT)
    tags = models.ManyToManyField(Tag)
    image = models.ImageField(default='', blank=True, upload_to='images')
    # image_thumbnail = ImageSpecField(source='image', processors=[ResizeToFill(350, 200)], format='JPEG', options={'quality':60})
    
    def __str__(self):
        return self.title
        
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Flower, self).save()
        
    def get_absolute_url(self): 
        return reverse('detail', args=[str(self.slug)])

base/views.py
from django.shortcuts import render

# Create your views here.

base/templates/base/base.html
{% load static %}

<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta name="description" content="">
		<meta name="author" content="">
		<link rel="icon" href="../../../../favicon.ico">
		<title>MySite</title>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
		<link rel="stylesheet" href="{% static 'base/css/site.css' %}">
	</head>

	<body>
		<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
			<a class="navbar-brand" href="/">MySite</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse" id="navbarsExampleDefault">
			<ul class="navbar-nav mr-auto">
			<li class="nav-item active">
				<a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="/news/">News<span class="sr-only"></span></a>
			</li>
			{% if perms.flower.add_flower %}
			<li class="nav-item">
				<a class="nav-link" href="/create/">Create Flower</a>
			</li>
			{% endif %}

			{% if request.user.is_authenticated %}
			<li class="nav-item">
				<a class="nav-link" href="/accounts/logout/">Logout</a>
			</li>
			{% else %}
			<li class="nav-item">
				<a class="nav-link" href="/accounts/login/">Login</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="/accounts/signup/">Sign Up</a>
			</li>
			{% endif %}
			</ul>
			</div>

			<form action="/" method="get" class="form-inline mt-2 mt-md-0">
			<input id="q" name="q" value="{{ request.GET.q }}" class="form-control mr-sm-2" type="text" placeholder="Search..." aria-label="Search">
			<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
			</form>

		</nav>

		<main role="main" class="container">

			<div class="starter-template">
			{% block content %}{% endblock %}
			</div>

		</main><!-- /.container -->

		<footer class="footer"> <!-- here -->
			<div class="container">
				<span class="text-muted">
				Reference: <a target="_blank" href="https://leanpub.com/django-the-easy-way">"Django - The Easy Way" </a>book.
				</span>
			</div>
		</footer>

		<!-- Bootstrap core JavaScript
		 ================================================== -->
		<!-- Placed at the end of the document so the pages load faster -->
		<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
	</body>
</html>